#include <cstdlib>
#include <cstring>
#include <deque>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <vector>

#include "../include/json.hpp"
#include "../include/Automat.h"
#include "../include/CFG.h"

using namespace std;
using json = nlohmann::json;


// ==========================================
// Task 1: Automaton and DFA Conversion
// ==========================================
void task1() {
    const int size = 2000;
    char inputBuffer[size];
    char inputWordBuffer[50]; 
    Automat firstAutomaton;
    Automat secondAutomaton;

    Input inputAux("../input.txt");
    Input input = inputAux;
    States states{input};
    Sigma sigma(input);
    Transitions transitions(input, states, sigma);

    firstAutomaton = Automat{input};
    secondAutomaton = firstAutomaton;

    if (!firstAutomaton.isValid()) {
        exit(0);
    }

    cout << secondAutomaton;
    firstAutomaton.toDFA();
    cout << "\n\nAutomaton converted to DFA\n\n";
    cout << firstAutomaton;

    while (true) {
        cout << "\n\nEnter the word to verify:\n\n";
        cin >> inputWordBuffer;
        cout << "(?)DFA: " << firstAutomaton.acceptsWord(inputWordBuffer)
             << "\n*NFA / (initial DFA): " << secondAutomaton.acceptsWord(inputWordBuffer)
             << "\n\n";
    }
}


// ==========================================
// Task 2: Regex to DFA and JSON Testing
// ==========================================
void task2() {
    ifstream file("../src/LFA-Assignment2_Regex_DFA.json");
    auto data = json::parse(file);

    for (auto example : data) {
        cout << "\n\nName: " << example["name"] << "\n"
             << "Regex: " << example["regex"] << "\n";

        string regex = example["regex"];
        Automat automaton(regex);
        automaton.toDFA();

        for (auto test : example["test_strings"]) {
            string inputWord = test["input"];
            bool result = automaton.belongsToAutomaton(inputWord);
            bool expected = test["expected"];

            cout << test["input"] << " : "
                 << ((result == 1) ? "true" : "false")
                 << " correct: " << test["expected"] << "\n";

            if (result != expected) {
                cout << "Mismatch!";
                exit(4);
            }
        }
    }
}


// ==========================================
// Task 3: Context-Free Grammar Processing
// ==========================================
void task3() {
    string filename = "../src/aSb.in";
    ifstream file(filename);
    if (!file.is_open()) {
        cout << "File doesn't exist: " << filename << "\n";
    }

    CFG grammar{filename};
    vector<string> generatedWords = grammar.generate(10, 10);
    cout << "Words generated by the grammar (maximum 10 words, each with a maximum of 10 characters): \n";
    for (int index = 0; index < generatedWords.size(); ++index) {
        cout << index + 1 << ")" << generatedWords[index] << "\n";
    }

    string inputWord = "aaabbb";
    vector<string> derivation = grammar.derivation(inputWord);
    cout << "Derivation of the word \"" << inputWord << "\"\n";
    for (int index = 0; index < derivation.size(); ++index) {
        cout << derivation[index];
        if (index != derivation.size() - 1) {
            cout << " -> ";
        } else {
            cout << "\n";
        }
    }

    string otherWord = "aaaabbb";
    bool isRecognized = grammar.recognize(otherWord);
    cout << "The word \"" << otherWord << "\" belongs to the grammar: ";
    if (isRecognized) {
        cout << "True";
    } else {
        cout << "False";
    }
    cout << "\n";
}


// ==========================================
// Bonus Task 3: Non-Context-Free Grammar
// ==========================================
void bonusTask3() {
    string filename = "../src/aNbNcN.in";
    ifstream file(filename);
    if (!file.is_open()) {
        cout << "File doesn't exist: " << filename << "\n";
    }

    /*
     The grammar explained in the seminar using the pumping lemma to show it is not context-free.
     Intuitively, we cannot implement a push-down automaton because we would need two stacks
     to remember the numbers of a, b, and c, which shows the grammar is not context-free.
     */

    CFG grammar{filename};
    vector<string> words = {"aabcc", "aabbc", "aaabbbccc", "bac"};

    for (auto currentWord : words) {
        auto verify = [](string &word) {
            int count = 0;
            int previousCount = 0;
            int index = 0;

            if (word.length() < 3) {
                return false;
            }

            while (word[index] == 'a') {
                ++count;
                ++index;
            }
            previousCount = count;

            while (word[index] == 'b') {
                --count;
                ++index;
            }
            if (count) {
                return false;
            }

            while (word[index] == 'c') {
                ++count;
                ++index;
            }
            if (count != previousCount) {
                return false;
            }
            return true;
        };

        cout << "The word \"" << currentWord << "\" belongs to the grammar? \n";
        cout << "CFG recognizer: ";
        bool isRecognized = grammar.recognize(currentWord);
        if (isRecognized) {
            cout << "True";
        } else {
            cout << "False";
        }

        cout << "\nVerification function:";
        bool isValid = verify(currentWord);
        if (isValid) {
            cout << "True";
        } else {
            cout << "False";
        }
        cout << "\n";

        if (isValid) {
            cout << "The derivation is:\n";
            vector<string> derivation = grammar.derivation(currentWord);
            for (int index = 0; index < derivation.size(); ++index) {
                cout << derivation[index];
                if (index != derivation.size() - 1) {
                    cout << " -> ";
                } else {
                    cout << "\n";
                }
            }
        } else {
            cout << "So the word does NOT belong to the grammar!\n";
        }
        cout << "\n";
    }
}


// ==========================================
// Custom CFG Entry point
// ==========================================
void cfgAny() {
    string inputLine;
    string filename = "../src/CFG.in";
    string answer;

    std::cout << "Read from CFG.in? (No/Yes)" << std::endl;
    std::cin >> answer;
    if (answer == "No") {
        cout << "Enter the grammar: (STOP at the end)" << std::endl;
        ofstream grammarFile(filename);
        while (getline(cin, inputLine) && inputLine != "STOP") {
            grammarFile << inputLine << "\n";
        }
        grammarFile.close();
    }

    CFG grammar(filename);
    vector<string> generatedWords = grammar.generate(10, 10);
    cout << "Words generated by the grammar (maximum 10 words, each with a maximum of 10 characters): \n";
    for (int index = 0; index < generatedWords.size(); ++index) {
        cout << index + 1 << ")" << generatedWords[index] << "\n";
    }

    cout << "Enter words:" << std::endl;
    while (getline(cin, inputLine) && inputLine != "STOP") {
        cout << "CFG recognizer: ";
        bool isRecognized = grammar.recognize(inputLine);
        cout << "The word \"" << inputLine << "\" belongs to the grammar: ";
        if (isRecognized) {
            cout << "True";
        } else {
            cout << "False";
        }
        cout << "\n\n";
    }
}


// ==========================================
// Main Entry Point
// ==========================================
int main() {
    task3();
    bonusTask3();
    // cfgAny();
    task1();

    return 0;
}