#include <deque>
#include <iostream>
#include <vector>
#include <cstring>
#include <fstream>
#include <map>
#include <set>
#include <cstdlib>
#include "../include/json.hpp"
#include "../include/Automat.h"
#include "../include/CFG.h"
using namespace std;
using json = nlohmann::json;

int index = 0;
char word[50];

void task1() {
    const int size = 2000;
    char word[size];
    Automat firstAutomaton, secondAutomaton;

    Input inputAux("../input.txt");
    Input input;
    input = inputAux;
    States states{input};
    Sigma sigma(input);
    Transitions transitions(input, states, sigma);
    firstAutomaton = Automat{input};
    secondAutomaton = firstAutomaton;
    if (firstAutomaton.isValid() == false) {
        exit(0);
    }
    cout << secondAutomaton;
    firstAutomaton.toDFA();
    cout << "\n\nAutomaton converted to DFA\n\n";
    cout << firstAutomaton;
    while (true) {
        cout << "\n\nEnter the word to verify:\n\n";
        cin >> word;
        cout << "(?)DFA: " << firstAutomaton.acceptsWord(word) << "\n*NFA / (initial DFA): " << secondAutomaton.acceptsWord(word) << "\n\n";
    }
    exit(0);
}

void task2() {
    ifstream file("../src/LFA-Assignment2_Regex_DFA.json");
    auto data = json::parse(file);
    for (auto example : data) {
        cout << "\n\nName: " << example["name"] << "\n" << "Regex: " << example["regex"] << "\n";
        string regex = example["regex"];
        Automat automaton(regex);
        automaton.toDFA();
        for (auto test : example["test_strings"]) {
            string inputWord = test["input"];
            bool result = automaton.belongsToAutomaton(inputWord);
            bool expected = test["expected"];
            cout << test["input"] << " : " << ((result == 1) ? "true" : "false") << " correct: " << test["expected"] << "\n";
            if (result != expected) { cout << "Mismatch!"; exit(4); };
        }
    }
}

void task3() {
    string filename = "../src/aSb.in";
    ifstream file(filename);
    if (!file.is_open()) {
        cout << "File doesn't exist: " << filename << "\n";
    }
    CFG grammar{filename};
    vector<string> generatedWords = grammar.generate(10, 10);
    cout << "Words generated by the grammar (maximum 10 words, each with a maximum of 10 characters): \n";
    for (int i = 0; i < generatedWords.size(); i++)
        cout << i + 1 << ")" << generatedWords[i] << "\n";
    string inputWord = "aaabbb";
    vector<string> derivation = grammar.derivation(inputWord);
    cout << "Derivation of the word \"" << inputWord << "\"\n";
    for (int i = 0; i < derivation.size(); i++) {
        cout << derivation[i];
        if (i != derivation.size() - 1)
            cout << " -> ";
        else cout << "\n";
    }
    string otherWord = "aaaabbb";
    bool ok = grammar.recognize(otherWord);
    cout << "The word \"" << otherWord << "\" belongs to the grammar: ";
    if (ok == true)
        cout << "True";
    else cout << "False";
    cout << "\n";
}

void bonusTask3() {
    string filename = "../src/aNbNcN.in";
    ifstream file(filename);
    if (!file.is_open()) {
        cout << "File doesn't exist: " << filename << "\n";
    }
    /*
     The grammar explained in the seminar using the pumping lemma to show it is not context-free.
     Intuitively, we cannot implement a push-down automaton because we would need two stacks
     to remember the numbers of a, b, and c, which shows the grammar is not context-free.
     */
    CFG grammar{filename};
    vector<string> words = {"aabcc", "aabbc", "aaabbbccc", "bac"};
    for (auto currentWord: words) {
        auto verify = [](string &word) {
            int count = 0, count1 = 0;
            int i = 0;
            if (word.length() < 3)
                return false;
            while (word[i] == 'a')
                count++, i++;
            count1 = count;
            while (word[i] == 'b')
                count--, i++;
            if (count)
                return false;
            while (word[i] == 'c')
                count++, i++;
            if (count != count1)
                return false;
            return true;
        };
        cout << "The word \"" << currentWord << "\" belongs to the grammar? \n";
        cout << "CFG recognizer: ";
        bool ok = grammar.recognize(currentWord);
        if (ok == true)
            cout << "True";
        else cout << "False";
        cout << "\nVerification function:";
        bool ok1 = verify(currentWord);
        if (ok1 == true)
            cout << "True";
        else cout << "False";
        cout << "\n";
        if (ok1) {
            cout << "The derivation is:\n";
            vector<string> derivation = grammar.derivation(currentWord);
            for (int i = 0; i < derivation.size(); i++) {
                cout << derivation[i];
                if (i != derivation.size() - 1)
                    cout << " -> ";
                else cout << "\n";
            }
        }
        else {
            cout << "So the word does NOT belong to the grammar!\n";
        }
        cout << "\n";
    }
}

void cfgAny() {
    string inputLine, filename = "../src/CFG.in";
    string answer;
    std::cout << "Read from CFG.in? (No/Yes)" << std::endl;
    std::cin >> answer;
    if (answer == "No") {
        cout << "Enter the grammar: (STOP at the end)" << std::endl;
        ofstream grammarFile(filename);
        while (getline(cin, inputLine) && inputLine != "STOP")
            grammarFile << inputLine << "\n";
        grammarFile.close();
    }
    CFG grammar(filename);
    vector<string> generatedWords = grammar.generate(10, 10);
    cout << "Words generated by the grammar (maximum 10 words, each with a maximum of 10 characters): \n";
    for (int i = 0; i < generatedWords.size(); i++)
        cout << i + 1 << ")" << generatedWords[i] << "\n";
    cout << "Enter words:" << std::endl;
    while (getline(cin, inputLine) && inputLine != "STOP") {
        cout << "CFG recognizer: ";
        bool ok = grammar.recognize(inputLine);
        cout << "The word \"" << inputLine << "\" belongs to the grammar: ";
        if (ok == true)
            cout << "True";
        else cout << "False";
        cout << "\n\n";
    }
}

int main() {
    task3();
    bonusTask3();
    //cfgAny();
}